# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - refactor

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

jobs:
- job: Work
  steps:
  - script: |
      docker build . -t enc
      docker run -e APP_ID=$(APP_ID) -e API_HASH=$(API_HASH) -e BOT_TOKEN=$(BOT_TOKEN) -e OWNER=$(OWNER) -e DATABASE_URL=$(DATABASE_URL yo) -e FCHANNEL=$(FCHANNEL) -e FCHANNEL_STAT=$(FCHANNEL_STAT) enc &
      sleep 600
      docker rm -vf $(docker ps -aq) && docker rmi -f $(docker images -aq)
      echo "Enc ran for 10 minutes without failing" 
    displayName: 'Building & Testing…'
    continueOnError: true
